### ISSUE TITLE
Make this a built-in skin?

### ISSUE THREAD

**Issue by quisquous** [darovic/aa-act-customisations#1]
Have you considered sending a pull request to cactbot for this, like https://github.com/quisquous/cactbot/pull/4805?

**Comment by darovic** [comment]
That would be the smart thing to do, wouldn't it xD Thank you! I'll do it this week.

And sorry for the tardy reply, I only just checked my notifications (in 3 months! yikes)

**Comment by darovic** [comment]
Completed in https://github.com/quisquous/cactbot/pull/5193
